### ISSUE TITLE
汉化有乱码 

### ISSUE THREAD

**Issue by singemazuo** [Lolisky/CK2_2.6.2_CN_Fix#41]
所有的文字 不过我是mac版的 可以运行没问题 就是文字是乱码 想问下你们用的是什么字体 我去下个

**Comment by singemazuo** [comment]
或者编码格式是什么UTF-8吗？

**Comment by Lolisky** [comment]
呃……本包的基础是52汉化包，52汉化包是通过破解主程序、使其默认以GB2312解码，在此基础上做汉化的。我围观过Mac的对应Application，不知道应该怎么移植…… @singemazuo

**Comment by shouhuanxiaoji** [comment]
linux版上也是乱码.....

**Comment by Lolisky** [comment]
手上只有win版主程序（exe）的双字节补丁，现阶段不可解
作为mac用户，我也只能在虚拟机上玩（
@shouhuanxiaoji
