### ISSUE TITLE
win 10 汉化乱码

### ISSUE THREAD

**Issue by AsamaTan** [Lolisky/CK2_2.6.2_CN_Fix#62]
如题，确定下载的是2.6.2版本，已经把补丁解压拉进去，没开mod/dlc,依旧乱码，求解

**Comment by Lolisky** [comment]
> 如题，确定下载的是2.6.2版本，已经把补丁解压拉进去，没开mod/dlc,依旧乱码，求解

这玩意是四年前做着玩的，不再提供调试。

我怀疑你缺这个：
https://github.com/Lolisky/Crusader-Kings-II-2.6.3-Chinese-Localization/releases/tag/base

还不行就不知道了。

**Comment by cupen** [comment]
3 代有官方中文。
